---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-clusterrole
  labels:
    relaxdiego.com: prometheus-operator
rules:
  - apiGroups: [""]
    resources: ["configmaps", "services"]
    verbs: ["get", "create"]

  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "create"]

  - apiGroups: ["relaxdiego.com"]
    resources: ["prometheusclusters"]
    verbs: ["watch"]
